spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/favorites
    username: xxx
    password: xxx

# Mybatis开启驼峰映射
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true